################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LIBXML2 "libxml2")
    if (PC_LIBXML2_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LIBXML2_CFLAGS} ${PC_LIBXML2_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LIBXML2_INCLUDE_HINTS ${PC_LIBXML2_INCLUDE_DIRS} ${PC_LIBXML2_INCLUDE_DIRS}/*)
        set(PC_LIBXML2_LIBRARY_HINTS ${PC_LIBXML2_LIBRARY_DIRS} ${PC_LIBXML2_LIBRARY_DIRS}/*)
    endif(PC_LIBXML2_FOUND)
endif (NOT MSVC)

find_path (
    LIBXML2_INCLUDE_DIRS
    NAMES libxml2.h
    HINTS ${PC_LIBXML2_INCLUDE_HINTS}
)

find_library (
    LIBXML2_LIBRARIES
    NAMES libxml2
    HINTS ${PC_LIBXML2_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LIBXML2
    REQUIRED_VARS LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIRS
)
mark_as_advanced(
    LIBXML2_FOUND
    LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
