################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_XML2 "xml2")
    if (PC_XML2_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_XML2_CFLAGS} ${PC_XML2_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_XML2_INCLUDE_HINTS ${PC_XML2_INCLUDE_DIRS} ${PC_XML2_INCLUDE_DIRS}/*)
        set(PC_XML2_LIBRARY_HINTS ${PC_XML2_LIBRARY_DIRS} ${PC_XML2_LIBRARY_DIRS}/*)
    endif(PC_XML2_FOUND)
endif (NOT MSVC)

find_path (
    XML2_INCLUDE_DIRS
    NAMES xml2.h
    HINTS ${PC_XML2_INCLUDE_HINTS}
)

find_library (
    XML2_LIBRARIES
    NAMES xml2
    HINTS ${PC_XML2_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    XML2
    REQUIRED_VARS XML2_LIBRARIES XML2_INCLUDE_DIRS
)
mark_as_advanced(
    XML2_FOUND
    XML2_LIBRARIES XML2_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
